// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDC-P5gtdSWUXkEzBFrAWCpI-j3e9PShA',
    appId: '1:280967336651:web:01031c0e9cf05394f9814e',
    messagingSenderId: '280967336651',
    projectId: 'sistema-indicacao',
    authDomain: 'sistema-indicacao.firebaseapp.com',
    storageBucket: 'sistema-indicacao.firebasestorage.app',
    measurementId: 'G-3WXWR9532H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARoYSBcz7yLI3r1BGHdAgKBdmkw2Y8OQg',
    appId: '1:280967336651:android:d94a97adfc1b6f24f9814e',
    messagingSenderId: '280967336651',
    projectId: 'sistema-indicacao',
    storageBucket: 'sistema-indicacao.firebasestorage.app',
  );
}
